import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import { runInNewContext } from "node:vm";

test('preparation renders before a thread exists and the same view gains a real link', () => {
  const html=readFileSync(new URL('../ui/work-progress.html',import.meta.url),'utf8');
  const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
  const elements=new Map();
  const element=()=>({setAttribute(k,v){this[k]=v;},removeAttribute(k){delete this[k];},append(){}});
  const context={document:{getElementById(id){if(!elements.has(id))elements.set(id,element());return elements.get(id);},createElement:element},Date};
  runInNewContext(script.slice(0,script.indexOf('async function refresh'))+'\nglobalThis.renderTest=render;',context);
  const work={name:'검증',status:'planning',progress:{total:0,succeeded:0}};
  context.renderTest({work,tasks:[]});
  assert.match(elements.get('preparation').textContent,/작업을 준비/);
  assert.equal(elements.get('summary').hidden,true);
  assert.equal(elements.get('primary').hidden,true);
  assert.equal(elements.get('task-structure').hidden,true);
  work.master={threadId:'01a07084-279e-7fa0-96a7-9937bfb80cc4'};
  work.status='running';
  context.renderTest({work,tasks:[]});
  assert.equal(elements.get('preparation').textContent,'');
  assert.equal(elements.get('primary').href,'codex://threads/01a07084-279e-7fa0-96a7-9937bfb80cc4');
  work.master=null;work.status='failed';
  context.renderTest({work,tasks:[]});
  assert.match(elements.get('preparation').textContent,/이동할 작업 대화가 없습니다/);
});

test("panel refresh preserves stale evidence, pauses hidden views, and prevents overlapping requests", async () => {
  const html = readFileSync(new URL("../ui/work-progress.html", import.meta.url), "utf8");
  const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
  const element = () => ({ dataset: {}, children: [], setAttribute(name,value) {this[name]=value;}, removeAttribute(name) {delete this[name];}, append(...items) { this.children.push(...items); }, replaceChildren() { this.children = []; } });
  const elements = new Map();
  let visibility, resolveFetch, calls = 0;
  const timers = new Map(); let nextTimer = 0;
  const document = { hidden: false, getElementById(id) { if (!elements.has(id)) elements.set(id, element()); return elements.get(id); }, createElement: element, addEventListener(_, callback) { visibility = callback; } };
  runInNewContext(script, { document, location: { href: "http://localhost/progress?viewToken=read" }, navigator: {}, URL, AbortController, Date,
    setTimeout(callback, delay) { const id = ++nextTimer; timers.set(id, { callback, delay }); return id; }, clearTimeout(id) { timers.delete(id); },
    fetch() { calls++; return new Promise(resolve => { resolveFetch = resolve; }); } });
  const refresh = elements.get("refresh").onclick;
  await refresh();
  assert.equal(calls, 1);
  const threadId = "01a07084-279e-7fa0-96a7-9937bfb80cc4";
  const snapshot = { work: { name: "<img onerror=bad>", status: "running", master:{threadId,label:'작업 열기'},progress: { total: 2, succeeded: 0, active: 1 } }, tasks: [{id:'test',name:"테스트",status:"running",threadId,dependsOn:['prepare']}, {id:'prepare',name:"준비",threadId:"javascript:bad"}] };
  resolveFetch({ ok: true, json: async () => snapshot });
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(elements.get("name").textContent, "<img onerror=bad>");
  const article = elements.get("tasks").children[0];
  assert.equal(article.children[2].href, `codex://threads/${threadId}`);
  assert.equal(article.children[2].textContent, "작업 열기");
  assert.equal(article.children[2].onclick, undefined);
  assert.equal(article.children[1].textContent,'준비 → 테스트');
  assert.equal(elements.get('primary').href,`codex://threads/${threadId}`);
  assert.equal(elements.get("tasks").children[1].children[2].hidden, true);
  assert.equal(elements.get("connection").dataset.error, "false");
  assert.ok([...timers.values()].some(timer => timer.delay === 5000));
  document.hidden = true; visibility(); await refresh();
  assert.equal(calls, 1);
  assert.equal(timers.size, 0);
  document.hidden = false; visibility();
  assert.equal(calls, 2);
  const link=article.children[2];
  snapshot.tasks[0].status='recovery_attention';snapshot.tasks[0].nextAction='inspect_execution_evidence';snapshot.tasks[0].issue='INTERNAL_ERROR';
  snapshot.work.status='failed';snapshot.work.progress.rejected=1;snapshot.work.needsAttention=true;
  snapshot.work.attention={cause:'검색 출력 관측을 확인해야 합니다.'};
  resolveFetch({ok:true,json:async()=>snapshot});
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(elements.get('tasks').children[0],article);
  assert.equal(article.children[2],link);
  assert.equal(elements.get('overall').textContent,'실패 · 결과 검증 거절');
  assert.equal(article.children.length,3);
  assert.equal(elements.has('attention'),false);
  assert.equal(elements.get('task-structure').hidden,false);
  assert.doesNotMatch(JSON.stringify(article),/INTERNAL_ERROR|검색 출력 관측/);
  void refresh();
  resolveFetch({ ok: false, status: 403 });
  await new Promise(resolve => setImmediate(resolve));
  assert.equal(elements.get("connection").dataset.error, "true");
  assert.match(elements.get("connection").textContent, /갱신 끊김.*연결 만료.*최신 상태가 아닐 수/);
  assert.equal(elements.get("name").textContent, "<img onerror=bad>");
});
